// Real Labubu Figure Database - Converted from authentic collector data
export type LabubuFigure = {
    id: number;
    name: string;
    series: string;
    color: string;
    size: string;
    rarity: 'Common' | 'Uncommon' | 'Rare' | 'Very Rare' | 'Ultra Rare';
    releaseDate: string;
    estimatedValue: { min: number; max: number };
    originalPrice: number;
    imageUrl: string;
    userImageUrl?: string; // Optional: user-uploaded photo URL (keeps catalog imageUrl intact)
    features: string[];
    description: string;
    dimensions: string;
    buyLink: string; // New field for Pop Mart purchase link
    ownedDate?: string; // Optional: when the user marked this as owned
};

export const labubuFigures: LabubuFigure[] = [
    // Exciting Macaron Series (V1) - 2023-10
    {
        id: 1,
        name: "Soy Milk Macaron",
        series: "Exciting Macaron Series (V1)",
        color: "Soy Milk Pastel",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "assets/soy-milk-macaron.jpg",
        features: ["Blind box set", "Pastel theme", "Macaron design", "Vinyl plush pendant"],
        description: "Labubu as soymilk macaron, pastel plush pendant from the classic hyped series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.amazon.com/stores/POPMART/page/123" // Fallback: often sold out on Pop Mart
    },
    {
        id: 2,
        name: "Pistachio Macaron",
        series: "Exciting Macaron Series (V1)",
        color: "Pistachio Green",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "assets/pistachio-macaron.jpg",
        features: ["Blind box set", "Green theme", "Macaron design", "Vinyl plush pendant"],
        description: "Labubu as pistachio macaron, green plush pendant from the classic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.amazon.com/stores/POPMART/page/123"
    },
    {
        id: 3,
        name: "Strawberry Macaron",
        series: "Exciting Macaron Series (V1)",
        color: "Strawberry Pink",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "assets/strawberry-macaron.jpg",
        features: ["Blind box set", "Pink theme", "Macaron design", "Vinyl plush pendant"],
        description: "Labubu as strawberry macaron, pink plush pendant from the classic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.amazon.com/stores/POPMART/page/123"
    },
    {
        id: 4,
        name: "Blueberry Macaron",
        series: "Exciting Macaron Series (V1)",
        color: "Blueberry Blue",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "assets/blueberry-macaron.jpg",
        features: ["Blind box set", "Blue theme", "Macaron design", "Vinyl plush pendant"],
        description: "Labubu as blueberry macaron, blue plush pendant from the classic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.amazon.com/stores/POPMART/page/123"
    },
    {
        id: 5,
        name: "Lemon Macaron",
        series: "Exciting Macaron Series (V1)",
        color: "Lemon Yellow",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "assets/lemon-macaron.jpg",
        features: ["Blind box set", "Yellow theme", "Macaron design", "Vinyl plush pendant"],
        description: "Labubu as lemon macaron, yellow plush pendant from the classic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.amazon.com/stores/POPMART/page/123"
    },
    {
        id: 6,
        name: "Matcha Macaron",
        series: "Exciting Macaron Series (V1)",
        color: "Matcha Green",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "assets/matcha-macaron.jpg",
        features: ["Blind box set", "Matcha theme", "Macaron design", "Vinyl plush pendant"],
        description: "Labubu as matcha macaron, green plush pendant from the classic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.amazon.com/stores/POPMART/page/123"
    },
    {
        id: 7,
        name: "Raspberry Macaron",
        series: "Exciting Macaron Series (V1)",
        color: "Raspberry Red",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "assets/raspberry-macaron.jpg",
        features: ["Blind box set", "Red theme", "Macaron design", "Vinyl plush pendant"],
        description: "Labubu as raspberry macaron, red plush pendant from the classic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.amazon.com/stores/POPMART/page/123"
    },
    {
        id: 8,
        name: "Chestnut Cocoa (Secret)",
        series: "Exciting Macaron Series (V1)",
        color: "Chestnut Brown",
        size: "17cm / 6.7 inches",
        rarity: "Ultra Rare",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 80, max: 150 },
        originalPrice: 17.50,
        imageUrl: "assets/chestnut-cocoa-secret.jpg",
        features: ["Secret variant", "1:72 odds", "Highly sought-after", "Premium design"],
        description: "Rare chestnut cocoa variant, highly sought-after pendant from the classic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.amazon.com/stores/POPMART/page/123"
    },
    // Have a Seat Series (V2) - 2024-07
    {
        id: 9,
        name: "Sit Pretty",
        series: "Have a Seat Series (V2)",
        color: "Relaxed Theme",
        size: "15cm / 5.9 inches",
        rarity: "Common",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "assets/sit-pretty.jpg",
        features: ["Seated pose", "Softer design", "Calmer theme", "Vinyl plush pendant"],
        description: "Labubu in a pretty seated pose, softer and calmer design from V2 series.",
        dimensions: "15cm / 5.9 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/50"
    },
    {
        id: 10,
        name: "Cozy Chair",
        series: "Have a Seat Series (V2)",
        color: "Cozy Theme",
        size: "15cm / 5.9 inches",
        rarity: "Common",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "assets/cozy-chair.jpg",
        features: ["Chair pose", "Cozy design", "Relaxed theme", "Vinyl plush pendant"],
        description: "Labubu in a cozy chair pose, relaxed and comfortable design.",
        dimensions: "15cm / 5.9 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/50"
    },
    {
        id: 11,
        name: "Lounge Time",
        series: "Have a Seat Series (V2)",
        color: "Lounge Theme",
        size: "15cm / 5.9 inches",
        rarity: "Common",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "assets/lounge-time.jpg",
        features: ["Lounge pose", "Relaxed design", "Chill theme", "Vinyl plush pendant"],
        description: "Labubu in a lounge time pose, relaxed and chill design.",
        dimensions: "15cm / 5.9 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/50"
    },
    {
        id: 12,
        name: "Relax Mode",
        series: "Have a Seat Series (V2)",
        color: "Relax Theme",
        size: "15cm / 5.9 inches",
        rarity: "Common",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "assets/relax-mode.jpg",
        features: ["Relaxed pose", "Chill design", "Calm theme", "Vinyl plush pendant"],
        description: "Labubu in relax mode, calm and peaceful design.",
        dimensions: "15cm / 5.9 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/50"
    },
    {
        id: 13,
        name: "Chill Spot",
        series: "Have a Seat Series (V2)",
        color: "Chill Theme",
        size: "15cm / 5.9 inches",
        rarity: "Common",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "assets/chill-spot.jpg",
        features: ["Chill pose", "Relaxed design", "Comfortable theme", "Vinyl plush pendant"],
        description: "Labubu in a chill spot pose, comfortable and relaxed design.",
        dimensions: "15cm / 5.9 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/50"
    },
    {
        id: 14,
        name: "Rest Easy",
        series: "Have a Seat Series (V2)",
        color: "Rest Theme",
        size: "15cm / 5.9 inches",
        rarity: "Common",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "assets/rest-easy.jpg",
        features: ["Rest pose", "Peaceful design", "Calm theme", "Vinyl plush pendant"],
        description: "Labubu in a rest easy pose, peaceful and calm design.",
        dimensions: "15cm / 5.9 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/50"
    },
    {
        id: 15,
        name: "DuoDuo (Secret)",
        series: "Have a Seat Series (V2)",
        color: "Party Theme",
        size: "15cm / 5.9 inches",
        rarity: "Ultra Rare",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 70, max: 120 },
        originalPrice: 17.50,
        imageUrl: "assets/duoduo-secret.jpg",
        features: ["Secret variant", "Seated pose", "Rare collectible", "Party theme"],
        description: "Rare DuoDuo secret variant, seated relaxed pose from V2 series.",
        dimensions: "15cm / 5.9 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/50"
    },
    // Fall in Wild (Keychain Pendant) - 2024-07
    {
        id: 16,
        name: "Fall in Wild (Keychain Pendant)",
        series: "Fall in Wild (Keychain Pendant)",
        color: "Wilderness Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 30, max: 45 },
        originalPrice: 30.99,
        imageUrl: "assets/fall-in-wild-keychain.jpg",
        features: ["Keychain-style pendant", "Vinyl face", "Soft plush body", "Bag charm", "Seasonal variant"],
        description: "Playful Labubu in wilderness-themed outfit, seasonal keychain variant; non-blind box release.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    // Let's Checkmate (Hanging Card Pendant) - 2025-02
    {
        id: 17,
        name: "Pawn Labubu",
        series: "Let's Checkmate (Hanging Card Pendant)",
        color: "Chess Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 17.50,
        imageUrl: "assets/pawn-labubu.jpg",
        features: ["Chess-themed pose", "Pawn design", "Vinyl plush pendant", "Strategic theme"],
        description: "Labubu as chess pawn, vinyl plush pendant with strategic chess theme.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/products/1897/the-monsters-let-s-checkmate-series-vinyl-plush-hanging-card"
    },
    {
        id: 18,
        name: "Knight Labubu",
        series: "Let's Checkmate (Hanging Card Pendant)",
        color: "Chess Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 17.50,
        imageUrl: "assets/knight-labubu.jpg",
        features: ["Chess-themed pose", "Knight design", "Vinyl plush pendant", "Strategic theme"],
        description: "Labubu as chess knight, vinyl plush pendant with strategic chess theme.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/products/1897/the-monsters-let-s-checkmate-series-vinyl-plush-hanging-card"
    },
    {
        id: 19,
        name: "Bishop Labubu",
        series: "Let's Checkmate (Hanging Card Pendant)",
        color: "Chess Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 17.50,
        imageUrl: "assets/bishop-labubu.jpg",
        features: ["Chess-themed pose", "Bishop design", "Vinyl plush pendant", "Strategic theme"],
        description: "Labubu as chess bishop, vinyl plush pendant with strategic chess theme.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/products/1897/the-monsters-let-s-checkmate-series-vinyl-plush-hanging-card"
    },
    {
        id: 20,
        name: "Rook Labubu",
        series: "Let's Checkmate (Hanging Card Pendant)",
        color: "Chess Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 17.50,
        imageUrl: "assets/rook-labubu.jpg",
        features: ["Chess-themed pose", "Rook design", "Vinyl plush pendant", "Strategic theme"],
        description: "Labubu as chess rook, vinyl plush pendant with strategic chess theme.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/products/1897/the-monsters-let-s-checkmate-series-vinyl-plush-hanging-card"
    },
    {
        id: 21,
        name: "Queen Labubu",
        series: "Let's Checkmate (Hanging Card Pendant)",
        color: "Chess Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 17.50,
        imageUrl: "assets/queen-labubu.jpg",
        features: ["Chess-themed pose", "Queen design", "Vinyl plush pendant", "Strategic theme"],
        description: "Labubu as chess queen, vinyl plush pendant with strategic chess theme.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/products/1897/the-monsters-let-s-checkmate-series-vinyl-plush-hanging-card"
    },
    {
        id: 22,
        name: "King Labubu",
        series: "Let's Checkmate (Hanging Card Pendant)",
        color: "Chess Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 17.50,
        imageUrl: "assets/king-labubu.jpg",
        features: ["Chess-themed pose", "King design", "Vinyl plush pendant", "Strategic theme"],
        description: "Labubu as chess king, vinyl plush pendant with strategic chess theme.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/products/1897/the-monsters-let-s-checkmate-series-vinyl-plush-hanging-card"
    },
    {
        id: 23,
        name: "Checkmate Variant (Secret)",
        series: "Let's Checkmate (Hanging Card Pendant)",
        color: "Chess Theme",
        size: "17cm / 6.7 inches",
        rarity: "Ultra Rare",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 80, max: 150 },
        originalPrice: 17.50,
        imageUrl: "assets/checkmate-secret.jpg",
        features: ["Secret variant", "Chess theme", "Rare collectible", "Strategic design"],
        description: "Rare checkmate variant, secret chess-themed pendant from the strategic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/products/1897/the-monsters-let-s-checkmate-series-vinyl-plush-hanging-card"
    },
    // The Monsters x One Piece Series - 2025-02
    {
        id: 24,
        name: "Labubu as Luffy",
        series: "The Monsters x One Piece Series",
        color: "One Piece Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "assets/labubu-luffy.jpg",
        features: ["One Piece collab", "Luffy cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Monkey D. Luffy from One Piece, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 25,
        name: "Labubu as Zoro",
        series: "The Monsters x One Piece Series",
        color: "One Piece Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "assets/labubu-zoro.jpg",
        features: ["One Piece collab", "Zoro cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Roronoa Zoro from One Piece, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 26,
        name: "Labubu as Nami",
        series: "The Monsters x One Piece Series",
        color: "One Piece Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "assets/labubu-nami.jpg",
        features: ["One Piece collab", "Nami cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Nami from One Piece, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 27,
        name: "Labubu as Usopp",
        series: "The Monsters x One Piece Series",
        color: "One Piece Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "assets/labubu-usopp.jpg",
        features: ["One Piece collab", "Usopp cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Usopp from One Piece, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 28,
        name: "Labubu as Sanji",
        series: "The Monsters x One Piece Series",
        color: "One Piece Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "assets/labubu-sanji.jpg",
        features: ["One Piece collab", "Sanji cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Sanji from One Piece, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 29,
        name: "Labubu as Chopper",
        series: "The Monsters x One Piece Series",
        color: "One Piece Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "assets/labubu-chopper.jpg",
        features: ["One Piece collab", "Chopper cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Tony Tony Chopper from One Piece, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 30,
        name: "Labubu as Robin",
        series: "The Monsters x One Piece Series",
        color: "One Piece Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "assets/labubu-robin.jpg",
        features: ["One Piece collab", "Robin cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Nico Robin from One Piece, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 31,
        name: "Labubu as Franky",
        series: "The Monsters x One Piece Series",
        color: "One Piece Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "assets/labubu-franky.jpg",
        features: ["One Piece collab", "Franky cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Franky from One Piece, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 32,
        name: "Labubu as Brook",
        series: "The Monsters x One Piece Series",
        color: "One Piece Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "assets/labubu-brook.jpg",
        features: ["One Piece collab", "Brook cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Brook from One Piece, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 33,
        name: "Labubu as Jinbe",
        series: "The Monsters x One Piece Series",
        color: "One Piece Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "assets/labubu-jinbe.jpg",
        features: ["One Piece collab", "Jinbe cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Jinbe from One Piece, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 34,
        name: "Labubu as Yamato",
        series: "The Monsters x One Piece Series",
        color: "One Piece Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "assets/labubu-yamato.jpg",
        features: ["One Piece collab", "Yamato cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Yamato from One Piece, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 35,
        name: "Labubu as Ace",
        series: "The Monsters x One Piece Series",
        color: "One Piece Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "assets/labubu-ace.jpg",
        features: ["One Piece collab", "Ace cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Portgas D. Ace from One Piece, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 36,
        name: "Labubu as Sabo",
        series: "The Monsters x One Piece Series",
        color: "One Piece Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "assets/labubu-sabo.jpg",
        features: ["One Piece collab", "Sabo cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Sabo from One Piece, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 37,
        name: "Rare Cosplay Variant (Secret)",
        series: "The Monsters x One Piece Series",
        color: "One Piece Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Ultra Rare",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 100, max: 180 },
        originalPrice: 19.99,
        imageUrl: "assets/one-piece-secret.jpg",
        features: ["Secret variant", "One Piece collab", "Rare collectible", "Special cosplay design"],
        description: "Rare cosplay variant from One Piece collaboration, secret collectible with special design.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    // Big into Energy Series (V3) - 2025-04
    {
        id: 38,
        name: "Luck",
        series: "Big into Energy Series (V3)",
        color: "Energy Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-04-01",
        estimatedValue: { min: 15, max: 30 },
        originalPrice: 17.50,
        imageUrl: "assets/luck-energy.jpg",
        features: ["Emotion-themed", "Colored teeth/nails", "Energy design", "Vinyl plush pendant"],
        description: "Labubu representing luck energy, emotion-themed with colored teeth and nails.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/195"
    },
    {
        id: 39,
        name: "Joy",
        series: "Big into Energy Series (V3)",
        color: "Energy Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-04-01",
        estimatedValue: { min: 15, max: 30 },
        originalPrice: 17.50,
        imageUrl: "assets/joy-energy.jpg",
        features: ["Emotion-themed", "Colored teeth/nails", "Energy design", "Vinyl plush pendant"],
        description: "Labubu representing joy energy, emotion-themed with colored teeth and nails.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/195"
    },
    {
        id: 40,
        name: "Courage",
        series: "Big into Energy Series (V3)",
        color: "Energy Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-04-01",
        estimatedValue: { min: 15, max: 30 },
        originalPrice: 17.50,
        imageUrl: "assets/courage-energy.jpg",
        features: ["Emotion-themed", "Colored teeth/nails", "Energy design", "Vinyl plush pendant"],
        description: "Labubu representing courage energy, emotion-themed with colored teeth and nails.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/195"
    },
    {
        id: 41,
        name: "Passion",
        series: "Big into Energy Series (V3)",
        color: "Energy Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-04-01",
        estimatedValue: { min: 15, max: 30 },
        originalPrice: 17.50,
        imageUrl: "assets/passion-energy.jpg",
        features: ["Emotion-themed", "Colored teeth/nails", "Energy design", "Vinyl plush pendant"],
        description: "Labubu representing passion energy, emotion-themed with colored teeth and nails.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/195"
    },
    {
        id: 42,
        name: "Peace",
        series: "Big into Energy Series (V3)",
        color: "Energy Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-04-01",
        estimatedValue: { min: 15, max: 30 },
        originalPrice: 17.50,
        imageUrl: "assets/peace-energy.jpg",
        features: ["Emotion-themed", "Colored teeth/nails", "Energy design", "Vinyl plush pendant"],
        description: "Labubu representing peace energy, emotion-themed with colored teeth and nails.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/195"
    },
    {
        id: 43,
        name: "Hope",
        series: "Big into Energy Series (V3)",
        color: "Energy Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-04-01",
        estimatedValue: { min: 15, max: 30 },
        originalPrice: 17.50,
        imageUrl: "assets/hope-energy.jpg",
        features: ["Emotion-themed", "Colored teeth/nails", "Energy design", "Vinyl plush pendant"],
        description: "Labubu representing hope energy, emotion-themed with colored teeth and nails.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/195"
    },
    {
        id: 44,
        name: "Rainbow Energy (Secret)",
        series: "Big into Energy Series (V3)",
        color: "Rainbow Theme",
        size: "17cm / 6.7 inches",
        rarity: "Ultra Rare",
        releaseDate: "2025-04-01",
        estimatedValue: { min: 80, max: 150 },
        originalPrice: 17.50,
        imageUrl: "assets/rainbow-energy-secret.jpg",
        features: ["Secret variant", "Rainbow energy", "Rare collectible", "Special design"],
        description: "Rare rainbow energy variant, secret collectible with special rainbow design.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/195"
    },
    // Wacky Mart Series - 2025-06-13
    {
        id: 45,
        name: "Snack Attack",
        series: "Wacky Mart Series",
        color: "Snack Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Common",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 19.99,
        imageUrl: "assets/snack-attack.jpg",
        features: ["Snack-themed", "Electronic components", "PVC/ABS figure", "Attitude design"],
        description: "Labubu in snack attack mode, snack-themed figure with electronic components and attitude design.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    {
        id: 46,
        name: "Candy Crush",
        series: "Wacky Mart Series",
        color: "Candy Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Common",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 19.99,
        imageUrl: "assets/candy-crush.jpg",
        features: ["Candy-themed", "Electronic components", "PVC/ABS figure", "Attitude design"],
        description: "Labubu in candy crush mode, candy-themed figure with electronic components and attitude design.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    {
        id: 47,
        name: "Popcorn Panic",
        series: "Wacky Mart Series",
        color: "Popcorn Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Common",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 19.99,
        imageUrl: "assets/popcorn-panic.jpg",
        features: ["Popcorn-themed", "Electronic components", "PVC/ABS figure", "Attitude design"],
        description: "Labubu in popcorn panic mode, popcorn-themed figure with electronic components and attitude design.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    {
        id: 48,
        name: "Soda Splash",
        series: "Wacky Mart Series",
        color: "Soda Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Common",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 19.99,
        imageUrl: "assets/soda-splash.jpg",
        features: ["Soda-themed", "Electronic components", "PVC/ABS figure", "Attitude design"],
        description: "Labubu in soda splash mode, soda-themed figure with electronic components and attitude design.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    {
        id: 49,
        name: "Chip Chaos",
        series: "Wacky Mart Series",
        color: "Chip Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Common",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 19.99,
        imageUrl: "assets/chip-chaos.jpg",
        features: ["Chip-themed", "Electronic components", "PVC/ABS figure", "Attitude design"],
        description: "Labubu in chip chaos mode, chip-themed figure with electronic components and attitude design.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    {
        id: 50,
        name: "Gum Gobble",
        series: "Wacky Mart Series",
        color: "Gum Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Common",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 19.99,
        imageUrl: "assets/gum-gobble.jpg",
        features: ["Gum-themed", "Electronic components", "PVC/ABS figure", "Attitude design"],
        description: "Labubu in gum gobble mode, gum-themed figure with electronic components and attitude design.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    {
        id: 51,
        name: "Ice Cream Insanity",
        series: "Wacky Mart Series",
        color: "Ice Cream Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Common",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 19.99,
        imageUrl: "assets/ice-cream-insanity.jpg",
        features: ["Ice cream-themed", "Electronic components", "PVC/ABS figure", "Attitude design"],
        description: "Labubu in ice cream insanity mode, ice cream-themed figure with electronic components and attitude design.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    {
        id: 52,
        name: "Wacky Cashier (Secret)",
        series: "Wacky Mart Series",
        color: "Cashier Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Ultra Rare",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 100, max: 185 },
        originalPrice: 19.99,
        imageUrl: "assets/wacky-cashier-secret.jpg",
        features: ["Secret variant", "Cashier design", "Electronic components", "Rare collectible"],
        description: "Rare wacky cashier variant, secret collectible with cashier design and electronic components.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    // Summer Ride Figure - 2025-08-15
    {
        id: 53,
        name: "Summer Ride Figure",
        series: "Summer Ride Figure",
        color: "Adventure Theme",
        size: "10cm / 3.94 inches",
        rarity: "Very Rare",
        releaseDate: "2025-08-15",
        estimatedValue: { min: 50, max: 80 },
        originalPrice: 39.99,
        imageUrl: "assets/summer-ride.jpg",
        features: ["Mountain bike", "Adventure theme", "Seasonal release", "Standalone figure", "PVC/ABS"],
        description: "Labubu on mountain bike, seasonal adventure theme; non-blind, standalone hyped release.",
        dimensions: "10cm / 3.94 inches",
        buyLink: "https://www.popmart.com/us/products/3448/labubu-summer-ride-figure"
    },
    // Pin for Love Series - 2025-08-28 (Sample of A-Z series)
    {
        id: 54,
        name: "A-Love",
        series: "Pin for Love Series",
        color: "Love Theme",
        size: "10.5cm / 4.13 inches (excluding loop)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 12.99,
        imageUrl: "assets/a-love.jpg",
        features: ["Letter A theme", "Mini pendant", "Love design", "Smaller scale", "Vinyl plush pendant"],
        description: "Labubu representing love with letter A theme, mini pendant one-third original size from the hyped recent drop.",
        dimensions: "10.5cm / 4.13 inches (excluding loop)",
        buyLink: "https://www.popmart.com/us/collection/174/pin-for-love"
    },
    {
        id: 55,
        name: "B-Hug",
        series: "Pin for Love Series",
        color: "Hug Theme",
        size: "10.5cm / 4.13 inches (excluding loop)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 12.99,
        imageUrl: "assets/b-hug.jpg",
        features: ["Letter B theme", "Mini pendant", "Hug design", "Smaller scale", "Vinyl plush pendant"],
        description: "Labubu representing hug with letter B theme, mini pendant one-third original size from the hyped recent drop.",
        dimensions: "10.5cm / 4.13 inches (excluding loop)",
        buyLink: "https://www.popmart.com/us/collection/174/pin-for-love"
    },
    {
        id: 56,
        name: "C-Kiss",
        series: "Pin for Love Series",
        color: "Kiss Theme",
        size: "10.5cm / 4.13 inches (excluding loop)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 12.99,
        imageUrl: "assets/c-kiss.jpg",
        features: ["Letter C theme", "Mini pendant", "Kiss design", "Smaller scale", "Vinyl plush pendant"],
        description: "Labubu representing kiss with letter C theme, mini pendant one-third original size from the hyped recent drop.",
        dimensions: "10.5cm / 4.13 inches (excluding loop)",
        buyLink: "https://www.popmart.com/us/collection/174/pin-for-love"
    },
    {
        id: 57,
        name: "Z-Eternal",
        series: "Pin for Love Series",
        color: "Eternal Theme",
        size: "10.5cm / 4.13 inches (excluding loop)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 12.99,
        imageUrl: "assets/z-eternal.jpg",
        features: ["Letter Z theme", "Mini pendant", "Eternal design", "Smaller scale", "Vinyl plush pendant"],
        description: "Labubu representing eternal with letter Z theme, mini pendant one-third original size from the hyped recent drop.",
        dimensions: "10.5cm / 4.13 inches (excluding loop)",
        buyLink: "https://www.popmart.com/us/collection/174/pin-for-love"
    },
    {
        id: 58,
        name: "Love Letter Variant (Secret)",
        series: "Pin for Love Series",
        color: "Love Letter Theme",
        size: "10.5cm / 4.13 inches (excluding loop)",
        rarity: "Ultra Rare",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 80, max: 150 },
        originalPrice: 12.99,
        imageUrl: "assets/love-letter-secret.jpg",
        features: ["Secret variant", "Love letter design", "Mini pendant", "Rare collectible", "Smaller scale"],
        description: "Rare love letter variant, secret collectible mini pendant from the very hyped recent drop.",
        dimensions: "10.5cm / 4.13 inches (excluding loop)",
        buyLink: "https://www.popmart.com/us/collection/174/pin-for-love"
    }
];
