// Real Labubu Figure Database - Converted from authentic collector data
export const LABUBU_FIGURES = [
  {
    id: 1,
    name: "Fall in Wild (Hanging Pendant)",
    series: "Labubu Core Edition",
    color: "Wilderness Theme",
    size: "Standard",
    rarity: "Common",
    releaseDate: "2024-07-12",
    estimatedValue: { min: 30, max: 45 },
    originalPrice: 30.99,
    imageUrl: "assets/fall-in-wild.jpg",
    features: ["Keychain-style pendant", "Vinyl face", "Soft plush body", "Bag charm"],
    description: "Playful Labubu in wilderness-themed outfit, vinyl face with soft plush body, attachable as bag charm.",
    dimensions: "8 x 7 x 17 cm (3.1 x 2.8 x 6.7 inches)"
  },
  {
    id: 2,
    name: "Let's Checkmate (Hanging Card Pendant)",
    series: "Labubu Core Edition",
    color: "Chess Theme",
    size: "Standard",
    rarity: "Common",
    releaseDate: "2025-02-07",
    estimatedValue: { min: 40, max: 60 },
    originalPrice: 39.99,
    imageUrl: "assets/lets-checkmate.jpg",
    features: ["Chess-themed pose", "Vinyl face plush", "Hanging clip", "Strategic design"],
    description: "Labubu in chess-themed pose, vinyl face plush with hanging clip, strategic and mischievous design.",
    dimensions: "17 cm (6.7 inches)"
  },
  {
    id: 3,
    name: "Happy Halloween Party - Sitting Pumpkin",
    series: "Labubu Seasonal Editions",
    color: "Halloween Orange",
    size: "Standard",
    rarity: "Rare",
    releaseDate: "2024-10-25",
    estimatedValue: { min: 50, max: 80 },
    originalPrice: 33.00,
    imageUrl: "assets/halloween-pumpkin.jpg",
    features: ["Seasonal limited", "Holiday exclusive", "Pumpkin theme", "Festive accents"],
    description: "Labubu as pumpkin for Halloween, vinyl face plush pendant with festive accents.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 4,
    name: "Close to Sweet",
    series: "Mokoko Series",
    color: "Pink",
    size: "Standard",
    rarity: "Common",
    releaseDate: "2023-09-01",
    estimatedValue: { min: 14, max: 25 },
    originalPrice: 14.00,
    imageUrl: "assets/close-to-sweet.jpg",
    features: ["Pink-furred Mokoko", "Heart nose", "Vinyl face", "Early pendant release"],
    description: "Cute pink-furred Mokoko with heart nose, vinyl face plush pendant for bags.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 5,
    name: "Fall into Spring",
    series: "Mokoko Series",
    color: "Spring Floral",
    size: "Standard",
    rarity: "Common",
    releaseDate: "2024-03-08",
    estimatedValue: { min: 22, max: 35 },
    originalPrice: 22.00,
    imageUrl: "assets/fall-into-spring.jpg",
    features: ["Spring floral theme", "Soft plush", "Vinyl face", "Seasonal"],
    description: "Mokoko in spring floral theme, soft plush with vinyl face, hanging pendant.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 6,
    name: "The Blue Diamond",
    series: "Mokoko Series",
    color: "Blue Diamond",
    size: "Standard",
    rarity: "Uncommon",
    releaseDate: "2024-06-18",
    estimatedValue: { min: 22, max: 40 },
    originalPrice: 22.00,
    imageUrl: "assets/blue-diamond.jpg",
    features: ["Sparkling diamond theme", "Gem accents", "Vinyl plush pendant"],
    description: "Mokoko with sparkling diamond theme, vinyl plush pendant.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 7,
    name: "Magic of Pumpkin (Halloween)",
    series: "Mokoko Series",
    color: "Halloween Theme",
    size: "Standard",
    rarity: "Rare",
    releaseDate: "2024-10-27",
    estimatedValue: { min: 22, max: 50 },
    originalPrice: 22.00,
    imageUrl: "assets/magic-pumpkin.jpg",
    features: ["Seasonal limited", "Pumpkin magic outfit", "Holiday collectors"],
    description: "Mokoko in pumpkin magic outfit, plush pendant for holiday collectors.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 8,
    name: "Twinkly Fairy Tale",
    series: "Mokoko Series",
    color: "Fairy Tale Sparkle",
    size: "Standard",
    rarity: "Common",
    releaseDate: "2024-11-28",
    estimatedValue: { min: 22, max: 35 },
    originalPrice: 22.00,
    imageUrl: "assets/twinkly-fairy-tale.jpg",
    features: ["Whimsical", "Fairy tale sparkle", "Vinyl face", "Hanging doll"],
    description: "Mokoko in fairy tale sparkle, vinyl face plush hanging doll.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 9,
    name: "Soymilk Macaron",
    series: "Labubu Exciting Macaron (V1)",
    color: "Soymilk Pastel",
    size: "Standard",
    rarity: "Common",
    releaseDate: "2023-10-01",
    estimatedValue: { min: 15, max: 25 },
    originalPrice: 17.50,
    imageUrl: "assets/soymilk-macaron.jpg",
    features: ["Blind box set", "Pastel theme", "Macaron design"],
    description: "Labubu as soymilk macaron, pastel plush pendant.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 10,
    name: "Lychee Berry Macaron",
    series: "Labubu Exciting Macaron (V1)",
    color: "Lychee Pink",
    size: "Standard",
    rarity: "Common",
    releaseDate: "2023-10-01",
    estimatedValue: { min: 15, max: 25 },
    originalPrice: 17.50,
    imageUrl: "assets/lychee-macaron.jpg",
    features: ["Dessert theme", "Vinyl plush", "Berry colors"],
    description: "Labubu in lychee berry dessert theme, vinyl plush.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 11,
    name: "Green Grape Macaron",
    series: "Labubu Exciting Macaron (V1)",
    color: "Green Grape",
    size: "Standard",
    rarity: "Common",
    releaseDate: "2023-10-01",
    estimatedValue: { min: 15, max: 25 },
    originalPrice: 17.50,
    imageUrl: "assets/green-grape-macaron.jpg",
    features: ["Green grape theme", "Cute design", "Pendant doll"],
    description: "Green grape macaron outfit, cute pendant doll.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 12,
    name: "Sea Salt Coconut Macaron",
    series: "Labubu Exciting Macaron (V1)",
    color: "Coconut White",
    size: "Standard",
    rarity: "Common",
    releaseDate: "2023-10-01",
    estimatedValue: { min: 15, max: 25 },
    originalPrice: 17.50,
    imageUrl: "assets/sea-salt-coconut.jpg",
    features: ["Tropical theme", "Sea salt coconut", "Plush pendant"],
    description: "Tropical sea salt coconut theme, plush pendant.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 13,
    name: "Toffee Macaron",
    series: "Labubu Exciting Macaron (V1)",
    color: "Toffee Brown",
    size: "Standard",
    rarity: "Common",
    releaseDate: "2023-10-01",
    estimatedValue: { min: 15, max: 25 },
    originalPrice: 17.50,
    imageUrl: "assets/toffee-macaron.jpg",
    features: ["Toffee dessert", "Vinyl face", "Sweet theme"],
    description: "Toffee dessert-inspired, vinyl face pendant.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 14,
    name: "Sesame Bean Macaron",
    series: "Labubu Exciting Macaron (V1)",
    color: "Sesame Beige",
    size: "Standard",
    rarity: "Common",
    releaseDate: "2023-10-01",
    estimatedValue: { min: 15, max: 25 },
    originalPrice: 17.50,
    imageUrl: "assets/sesame-bean.jpg",
    features: ["Sesame bean theme", "Soft plush", "Macaron series"],
    description: "Sesame bean macaron, soft plush doll.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 15,
    name: "Chestnut Cocoa (Secret)",
    series: "Labubu Exciting Macaron (V1)",
    color: "Chestnut Brown",
    size: "Standard",
    rarity: "Ultra Rare",
    releaseDate: "2023-10-01",
    estimatedValue: { min: 80, max: 150 },
    originalPrice: 17.50,
    imageUrl: "assets/chestnut-cocoa-secret.jpg",
    features: ["Secret variant", "1:72 odds", "Highly sought-after", "Premium design"],
    description: "Rare chestnut cocoa variant, highly sought-after pendant.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 16,
    name: "DuoDuo (Secret)",
    series: "Labubu Have a Seat (V2)",
    color: "Party Theme",
    size: "Standard",
    rarity: "Ultra Rare",
    releaseDate: "2024-07-01",
    estimatedValue: { min: 70, max: 120 },
    originalPrice: 17.50,
    imageUrl: "assets/duoduo-secret.jpg",
    features: ["Secret variant", "Seated pose", "Rare collectible", "Party theme"],
    description: "Seated relaxed pose, vinyl plush pendant from party theme.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 17,
    name: "Dynamic Pose Energy Series",
    series: "Labubu Big Into Energy (V3)",
    color: "Vibrant Multi",
    size: "Standard",
    rarity: "Uncommon",
    releaseDate: "2025-04-25",
    estimatedValue: { min: 15, max: 30 },
    originalPrice: 17.50,
    imageUrl: "assets/dynamic-energy.jpg",
    features: ["Energetic poses", "Jumping/running", "Vibrant colors", "Motivational series"],
    description: "Energetic jumping/running poses, vinyl face plush pendants in vibrant colors.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 18,
    name: "Catch Me If You Like Me (Valentine's)",
    series: "Labubu Seasonal Editions",
    color: "Black/Pink Romance",
    size: "Large",
    rarity: "Very Rare",
    releaseDate: "2024-01-12",
    estimatedValue: { min: 90, max: 150 },
    originalPrice: 99.99,
    imageUrl: "assets/valentine-catch-me.jpg",
    features: ["Limited 5000 units", "Valentine's exclusive", "Heart elements", "Premium size"],
    description: "Romantic Labubu pendant, vinyl plush with heart elements.",
    dimensions: "11 x 8 x 22 cm (4.3 x 3.1 x 8.7 inches)"
  },
  {
    id: 19,
    name: "OLDSKOOL MONSTERS FOREVER X Vans",
    series: "Labubu Collaborations",
    color: "Streetwear Theme",
    size: "Standard",
    rarity: "Very Rare",
    releaseDate: "2023-12-23",
    estimatedValue: { min: 80, max: 140 },
    originalPrice: 85.00,
    imageUrl: "assets/vans-collab.jpg",
    features: ["Limited 6654 units", "Vans collaboration", "Streetwear design", "Exclusive collab"],
    description: "Vans collab pendant, streetwear-themed Labubu plush.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 20,
    name: "BE FANCY NOW (PRONOUNCE Collab)",
    series: "Labubu Collaborations",
    color: "Elegant Fashion",
    size: "Standard",
    rarity: "Very Rare",
    releaseDate: "2024-03-15",
    estimatedValue: { min: 80, max: 140 },
    originalPrice: 85.00,
    imageUrl: "assets/pronounce-collab.jpg",
    features: ["Limited 6458 units", "Fashion collaboration", "Elegant design", "Premium collab"],
    description: "Elegant fashion collab, vinyl face plush pendant.",
    dimensions: "~17 cm (6.7 inches)"
  },
  {
    id: 21,
    name: "WINGS OF FANTASY, WINGS OF FORTUNE",
    series: "Labubu Collaborations",
    color: "Fantasy Wings",
    size: "Large",
    rarity: "Very Rare",
    releaseDate: "2024-01-01",
    estimatedValue: { min: 120, max: 200 },
    originalPrice: 119.99,
    imageUrl: "assets/wings-fantasy.jpg",
    features: ["Limited edition", "Winged theme", "Fantasy design", "Premium collectible"],
    description: "Fantasy winged Labubu pendant, soft plush with vinyl details.",
    dimensions: "11 x 8 x 22 cm (4.3 x 3.1 x 8.7 inches)"
  }
];
export default LABUBU_FIGURES;