// Real Labubu Figure Database - Converted from authentic collector data
export type LabubuFigure = {
    id: number;
    name: string;
    series: string;
    color: string;
    size: string;
    rarity: 'Common' | 'Uncommon' | 'Rare' | 'Very Rare' | 'Ultra Rare';
    releaseDate: string;
    estimatedValue: { min: number; max: number };
    originalPrice: number;
    imageUrl: string;
    features: string[];
    description: string;
    dimensions: string;
    buyLink: string;
};

export const labubuFigures: LabubuFigure[] = [
    // Exciting Macaron Series (V1) - October 2023 - 7 regulars + 1 secret
    {
        id: 1,
        name: "Soy Milk",
        series: "Exciting Macaron Series (V1)",
        color: "Off-white",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fsoy-milk.jpg?alt=media",
        features: ["Blind box set", "Pastel theme", "Macaron design", "Vinyl plush pendant"],
        description: "Labubu as soy milk macaron, pastel plush pendant from the classic hyped series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+macaron+soy+milk"
    },
    {
        id: 2,
        name: "Toffee",
        series: "Exciting Macaron Series (V1)",
        color: "Light brown",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Ftoffee.jpg?alt=media",
        features: ["Blind box set", "Brown theme", "Macaron design", "Vinyl plush pendant"],
        description: "Labubu as toffee macaron, brown plush pendant from the classic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+macaron+toffee"
    },
    {
        id: 3,
        name: "Lychee Berry",
        series: "Exciting Macaron Series (V1)",
        color: "Pink",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flychee-berry.jpg?alt=media",
        features: ["Blind box set", "Pink theme", "Macaron design", "Vinyl plush pendant"],
        description: "Labubu as lychee berry macaron, pink plush pendant from the classic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+macaron+lychee"
    },
    {
        id: 4,
        name: "Sea Salt Coconut",
        series: "Exciting Macaron Series (V1)",
        color: "Blue",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fsea-salt-coconut.jpg?alt=media",
        features: ["Blind box set", "Blue theme", "Macaron design", "Vinyl plush pendant"],
        description: "Labubu as sea salt coconut macaron, blue plush pendant from the classic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+macaron+sea+salt"
    },
    {
        id: 5,
        name: "Sesame Bean",
        series: "Exciting Macaron Series (V1)",
        color: "Grey",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fsesame-bean.jpg?alt=media",
        features: ["Blind box set", "Grey theme", "Macaron design", "Vinyl plush pendant"],
        description: "Labubu as sesame bean macaron, grey plush pendant from the classic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+macaron+sesame"
    },
    {
        id: 6,
        name: "Green Grape",
        series: "Exciting Macaron Series (V1)",
        color: "Green",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 25, max: 65 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fgreen-grape.jpg?alt=media",
        features: ["Blind box set", "Green theme", "Macaron design", "Vinyl plush pendant"],
        description: "Labubu as green grape macaron, popular green plush pendant from the classic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+macaron+green+grape"
    },
    {
        id: 7,
        name: "Raspberry Macaron",
        series: "Exciting Macaron Series (V1)",
        color: "Red",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fraspberry-macaron.jpg?alt=media",
        features: ["Blind box set", "Red theme", "Macaron design", "Vinyl plush pendant"],
        description: "Labubu as raspberry macaron, red plush pendant from the classic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+macaron+raspberry"
    },
    {
        id: 8,
        name: "Chestnut Cocoa (Secret)",
        series: "Exciting Macaron Series (V1)",
        color: "Brown",
        size: "17cm / 6.7 inches",
        rarity: "Ultra Rare",
        releaseDate: "2023-10-01",
        estimatedValue: { min: 80, max: 150 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fchestnut-cocoa-secret.jpg?alt=media",
        features: ["Secret variant", "1:72 odds", "Highly sought-after", "Premium design"],
        description: "Rare chestnut cocoa macaron, secret variant from the classic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+macaron+secret"
    },
    // Have a Seat Series (V2) - July 2024 - 6 regulars + 1 secret
    {
        id: 9,
        name: "BaBa",
        series: "Have a Seat Series (V2)",
        color: "Light brown",
        size: "15cm / 5.9 inches",
        rarity: "Common",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fbaba.jpg?alt=media",
        features: ["Seated pose", "Softer design", "Calmer theme", "Vinyl plush pendant"],
        description: "Labubu as BaBa, relaxed seated pose from the Have a Seat series.",
        dimensions: "15cm / 5.9 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/50"
    },
    {
        id: 10,
        name: "HeHe",
        series: "Have a Seat Series (V2)",
        color: "Greyish",
        size: "15cm / 5.9 inches",
        rarity: "Common",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fhehe.jpg?alt=media",
        features: ["Seated pose", "Softer design", "Calmer theme", "Vinyl plush pendant"],
        description: "Labubu as HeHe, relaxed seated pose from the Have a Seat series.",
        dimensions: "15cm / 5.9 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/50"
    },
    {
        id: 11,
        name: "SiSi",
        series: "Have a Seat Series (V2)",
        color: "Salmon",
        size: "15cm / 5.9 inches",
        rarity: "Common",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fsisi.jpg?alt=media",
        features: ["Seated pose", "Softer design", "Calmer theme", "Vinyl plush pendant"],
        description: "Labubu as SiSi, relaxed seated pose from the Have a Seat series.",
        dimensions: "15cm / 5.9 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/50"
    },
    {
        id: 12,
        name: "QuQu",
        series: "Have a Seat Series (V2)",
        color: "Lime green",
        size: "15cm / 5.9 inches",
        rarity: "Common",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fququ.jpg?alt=media",
        features: ["Seated pose", "Softer design", "Calmer theme", "Vinyl plush pendant"],
        description: "Labubu as QuQu, relaxed seated pose from the Have a Seat series.",
        dimensions: "15cm / 5.9 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/50"
    },
    {
        id: 13,
        name: "DaDa",
        series: "Have a Seat Series (V2)",
        color: "Light pink",
        size: "15cm / 5.9 inches",
        rarity: "Common",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fdada.jpg?alt=media",
        features: ["Seated pose", "Softer design", "Calmer theme", "Vinyl plush pendant"],
        description: "Labubu as DaDa, relaxed seated pose from the Have a Seat series.",
        dimensions: "15cm / 5.9 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/50"
    },
    {
        id: 14,
        name: "ZiZi",
        series: "Have a Seat Series (V2)",
        color: "Light purple",
        size: "15cm / 5.9 inches",
        rarity: "Common",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fzizi.jpg?alt=media",
        features: ["Seated pose", "Softer design", "Calmer theme", "Vinyl plush pendant"],
        description: "Labubu as ZiZi, relaxed seated pose from the Have a Seat series.",
        dimensions: "15cm / 5.9 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/50"
    },
    {
        id: 15,
        name: "DuoDuo (Secret)",
        series: "Have a Seat Series (V2)",
        color: "Dark brown",
        size: "15cm / 5.9 inches",
        rarity: "Ultra Rare",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 70, max: 120 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fduoduo-secret.jpg?alt=media",
        features: ["Secret variant", "1:72 odds", "Seated pose", "Rare collectible", "Party theme"],
        description: "Rare DuoDuo secret variant, seated relaxed pose from the Have a Seat series.",
        dimensions: "15cm / 5.9 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+have+a+seat+duoduo"
    },
    // Fall in Wild (Keychain Pendant) - July 2024 - 1 figure
    {
        id: 16,
        name: "Fall in Wild (Keychain Pendant)",
        series: "Fall in Wild (Keychain Pendant)",
        color: "Wilderness Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2024-07-01",
        estimatedValue: { min: 30, max: 45 },
        originalPrice: 30.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Ffall-in-wild-keychain.jpg?alt=media",
        features: ["Keychain-style pendant", "Vinyl face", "Soft plush body", "Bag charm", "Seasonal variant"],
        description: "Playful Labubu in wilderness-themed outfit, seasonal keychain variant; non-blind box release.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    // Let's Checkmate (Hanging Card Pendant) - February 2025 - 6 regulars + 1 secret
    {
        id: 17,
        name: "Pawn Labubu",
        series: "Let's Checkmate (Hanging Card Pendant)",
        color: "Chess Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fpawn-labubu.jpg?alt=media",
        features: ["Chess-themed pose", "Pawn design", "Hanging card pendant", "Strategic theme"],
        description: "Labubu as chess pawn, hanging card pendant with strategic chess theme.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/products/1897/the-monsters-let-s-checkmate-series-vinyl-plush-hanging-card"
    },
    {
        id: 18,
        name: "Knight Labubu",
        series: "Let's Checkmate (Hanging Card Pendant)",
        color: "Chess Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fknight-labubu.jpg?alt=media",
        features: ["Chess-themed pose", "Knight design", "Hanging card pendant", "Strategic theme"],
        description: "Labubu as chess knight, hanging card pendant with strategic chess theme.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/products/1897/the-monsters-let-s-checkmate-series-vinyl-plush-hanging-card"
    },
    {
        id: 19,
        name: "Bishop Labubu",
        series: "Let's Checkmate (Hanging Card Pendant)",
        color: "Chess Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fbishop-labubu.jpg?alt=media",
        features: ["Chess-themed pose", "Bishop design", "Hanging card pendant", "Strategic theme"],
        description: "Labubu as chess bishop, hanging card pendant with strategic chess theme.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/products/1897/the-monsters-let-s-checkmate-series-vinyl-plush-hanging-card"
    },
    {
        id: 20,
        name: "Rook Labubu",
        series: "Let's Checkmate (Hanging Card Pendant)",
        color: "Chess Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Frook-labubu.jpg?alt=media",
        features: ["Chess-themed pose", "Rook design", "Hanging card pendant", "Strategic theme"],
        description: "Labubu as chess rook, hanging card pendant with strategic chess theme.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/products/1897/the-monsters-let-s-checkmate-series-vinyl-plush-hanging-card"
    },
    {
        id: 21,
        name: "Queen Labubu",
        series: "Let's Checkmate (Hanging Card Pendant)",
        color: "Chess Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fqueen-labubu.jpg?alt=media",
        features: ["Chess-themed pose", "Queen design", "Hanging card pendant", "Strategic theme"],
        description: "Labubu as chess queen, hanging card pendant with strategic chess theme.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/products/1897/the-monsters-let-s-checkmate-series-vinyl-plush-hanging-card"
    },
    {
        id: 22,
        name: "King Labubu",
        series: "Let's Checkmate (Hanging Card Pendant)",
        color: "Chess Theme",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fking-labubu.jpg?alt=media",
        features: ["Chess-themed pose", "King design", "Hanging card pendant", "Strategic theme"],
        description: "Labubu as chess king, hanging card pendant with strategic chess theme.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/products/1897/the-monsters-let-s-checkmate-series-vinyl-plush-hanging-card"
    },
    {
        id: 23,
        name: "Checkmate Variant (Secret)",
        series: "Let's Checkmate (Hanging Card Pendant)",
        color: "Chess Theme",
        size: "17cm / 6.7 inches",
        rarity: "Ultra Rare",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 80, max: 150 },
        originalPrice: 17.50,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fcheckmate-secret.jpg?alt=media",
        features: ["Secret variant", "1:72 odds", "Chess theme", "Rare collectible", "Strategic design"],
        description: "Rare checkmate variant, secret chess-themed pendant from the strategic series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+checkmate+secret"
    },
    // The Monsters x One Piece Series - February 2025 - 14 regulars + 1 secret
    {
        id: 24,
        name: "Labubu as Luffy",
        series: "The Monsters x One Piece Series",
        color: "Straw Hat Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flabubu-luffy.jpg?alt=media",
        features: ["One Piece collab", "Luffy cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Monkey D. Luffy, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 25,
        name: "Labubu as Zoro",
        series: "The Monsters x One Piece Series",
        color: "Green Swordsman Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flabubu-zoro.jpg?alt=media",
        features: ["One Piece collab", "Zoro cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Roronoa Zoro, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 26,
        name: "Labubu as Nami",
        series: "The Monsters x One Piece Series",
        color: "Orange Navigator Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flabubu-nami.jpg?alt=media",
        features: ["One Piece collab", "Nami cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Nami, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 27,
        name: "Labubu as Usopp",
        series: "The Monsters x One Piece Series",
        color: "Yellow Sniper Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flabubu-usopp.jpg?alt=media",
        features: ["One Piece collab", "Usopp cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Usopp, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 28,
        name: "Labubu as Sanji",
        series: "The Monsters x One Piece Series",
        color: "Black Leg Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flabubu-sanji.jpg?alt=media",
        features: ["One Piece collab", "Sanji cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Sanji, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 29,
        name: "Labubu as Chopper",
        series: "The Monsters x One Piece Series",
        color: "Pink Reindeer Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flabubu-chopper.jpg?alt=media",
        features: ["One Piece collab", "Chopper cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Tony Tony Chopper, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 30,
        name: "Labubu as Robin",
        series: "The Monsters x One Piece Series",
        color: "Blue Archaeologist Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flabubu-robin.jpg?alt=media",
        features: ["One Piece collab", "Robin cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Nico Robin, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 31,
        name: "Labubu as Franky",
        series: "The Monsters x One Piece Series",
        color: "Cyborg Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flabubu-franky.jpg?alt=media",
        features: ["One Piece collab", "Franky cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Franky, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 32,
        name: "Labubu as Brook",
        series: "The Monsters x One Piece Series",
        color: "Skeleton Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flabubu-brook.jpg?alt=media",
        features: ["One Piece collab", "Brook cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Brook, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 33,
        name: "Labubu as Jinbe",
        series: "The Monsters x One Piece Series",
        color: "Fishman Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flabubu-jinbe.jpg?alt=media",
        features: ["One Piece collab", "Jinbe cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Jinbe, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 34,
        name: "Labubu as Yamato",
        series: "The Monsters x One Piece Series",
        color: "White Fang Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flabubu-yamato.jpg?alt=media",
        features: ["One Piece collab", "Yamato cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Yamato, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 35,
        name: "Labubu as Ace",
        series: "The Monsters x One Piece Series",
        color: "Fire Fist Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flabubu-ace.jpg?alt=media",
        features: ["One Piece collab", "Ace cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Portgas D. Ace, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 36,
        name: "Labubu as Sabo",
        series: "The Monsters x One Piece Series",
        color: "Revolutionary Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Common",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 25, max: 40 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flabubu-sabo.jpg?alt=media",
        features: ["One Piece collab", "Sabo cosplay", "Smaller figure", "Vinyl figure blind box"],
        description: "Labubu cosplaying as Sabo, collaboration series with smaller figures.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.popmart.com/us/collections/the-monsters"
    },
    {
        id: 37,
        name: "Rare Cosplay Variant (Secret)",
        series: "The Monsters x One Piece Series",
        color: "One Piece Theme",
        size: "8-10cm / 3-4 inches",
        rarity: "Ultra Rare",
        releaseDate: "2025-02-01",
        estimatedValue: { min: 100, max: 180 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fone-piece-secret.jpg?alt=media",
        features: ["Secret variant", "1:72 odds", "One Piece collab", "Rare collectible", "Special cosplay design"],
        description: "Rare cosplay variant from One Piece collaboration, secret collectible with special design.",
        dimensions: "8-10cm / 3-4 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+one+piece+secret"
    },
    // Big into Energy Series (V3) - April 2025 - 8 regulars + 1 secret
    {
        id: 38,
        name: "Love",
        series: "Big into Energy Series (V3)",
        color: "Red",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-04-01",
        estimatedValue: { min: 15, max: 30 },
        originalPrice: 27.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flove-energy.jpg?alt=media",
        features: ["Emotion-themed", "Tie-dye technique", "Energy design", "Vinyl plush pendant"],
        description: "Labubu representing love energy, tie-dye pendant from Big into Energy series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/195"
    },
    {
        id: 39,
        name: "Happiness",
        series: "Big into Energy Series (V3)",
        color: "Light pink (maybe salmon)",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-04-01",
        estimatedValue: { min: 15, max: 30 },
        originalPrice: 27.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fhappiness-energy.jpg?alt=media",
        features: ["Emotion-themed", "Tie-dye technique", "Energy design", "Vinyl plush pendant"],
        description: "Labubu representing happiness energy, tie-dye pendant from Big into Energy series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/195"
    },
    {
        id: 40,
        name: "Loyalty",
        series: "Big into Energy Series (V3)",
        color: "Mix of yellow, pink, reddish-orange",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-04-01",
        estimatedValue: { min: 15, max: 30 },
        originalPrice: 27.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Floyalty-energy.jpg?alt=media",
        features: ["Emotion-themed", "Tie-dye technique", "Energy design", "Vinyl plush pendant"],
        description: "Labubu representing loyalty energy, tie-dye pendant from Big into Energy series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/195"
    },
    {
        id: 41,
        name: "Serenity",
        series: "Big into Energy Series (V3)",
        color: "Green/light greenish",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-04-01",
        estimatedValue: { min: 15, max: 30 },
        originalPrice: 27.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fserenity-energy.jpg?alt=media",
        features: ["Emotion-themed", "Tie-dye technique", "Energy design", "Vinyl plush pendant"],
        description: "Labubu representing serenity energy, tie-dye pendant from Big into Energy series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/195"
    },
    {
        id: 42,
        name: "Hope",
        series: "Big into Energy Series (V3)",
        color: "Blue/light blue",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-04-01",
        estimatedValue: { min: 15, max: 30 },
        originalPrice: 27.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fhope-energy.jpg?alt=media",
        features: ["Emotion-themed", "Tie-dye technique", "Energy design", "Vinyl plush pendant"],
        description: "Labubu representing hope energy, tie-dye pendant from Big into Energy series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/195"
    },
    {
        id: 43,
        name: "Luck",
        series: "Big into Energy Series (V3)",
        color: "Purple, blue, pinkish",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-04-01",
        estimatedValue: { min: 15, max: 30 },
        originalPrice: 27.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fluck-energy.jpg?alt=media",
        features: ["Emotion-themed", "Tie-dye technique", "Energy design", "Vinyl plush pendant"],
        description: "Labubu representing luck energy, tie-dye pendant from Big into Energy series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/195"
    },
    {
        id: 44,
        name: "Courage",
        series: "Big into Energy Series (V3)",
        color: "TBD",
        size: "17cm / 6.7 inches",
        rarity: "Common",
        releaseDate: "2025-04-01",
        estimatedValue: { min: 15, max: 30 },
        originalPrice: 27.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fcourage-energy.jpg?alt=media",
        features: ["Emotion-themed", "Tie-dye technique", "Energy design", "Vinyl plush pendant"],
        description: "Labubu representing courage energy, tie-dye pendant from Big into Energy series (TBD).",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.popmart.com/us/pop-now/set/195"
    },
    {
        id: 45,
        name: "Id (Secret)",
        series: "Big into Energy Series (V3)",
        color: "Grey and black",
        size: "17cm / 6.7 inches",
        rarity: "Ultra Rare",
        releaseDate: "2025-04-01",
        estimatedValue: { min: 80, max: 150 },
        originalPrice: 27.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fid-secret.jpg?alt=media",
        features: ["Secret variant", "1:72 odds", "Rainbow energy", "Rare collectible", "Special design"],
        description: "Rare Id secret variant, collectible with special rainbow design from Big into Energy series.",
        dimensions: "17cm / 6.7 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+big+into+energy+id"
    },
    // Wacky Mart Series - June 2025 - 7 regulars + 1 secret
    {
        id: 46,
        name: "Snack Attack",
        series: "Wacky Mart Series",
        color: "Snack Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Common",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fsnack-attack.jpg?alt=media",
        features: ["Snack-themed", "Electronic components", "PVC/ABS figure", "Attitude design"],
        description: "Labubu in snack attack mode, snack-themed figure with electronic components and attitude design.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    {
        id: 47,
        name: "Candy Crush",
        series: "Wacky Mart Series",
        color: "Candy Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Common",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fcandy-crush.jpg?alt=media",
        features: ["Candy-themed", "Electronic components", "PVC/ABS figure", "Attitude design"],
        description: "Labubu in candy crush mode, candy-themed figure with electronic components and attitude design.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    {
        id: 48,
        name: "Popcorn Panic",
        series: "Wacky Mart Series",
        color: "Popcorn Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Common",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fpopcorn-panic.jpg?alt=media",
        features: ["Popcorn-themed", "Electronic components", "PVC/ABS figure", "Attitude design"],
        description: "Labubu in popcorn panic mode, popcorn-themed figure with electronic components and attitude design.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    {
        id: 49,
        name: "Soda Splash",
        series: "Wacky Mart Series",
        color: "Soda Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Common",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fsoda-splash.jpg?alt=media",
        features: ["Soda-themed", "Electronic components", "PVC/ABS figure", "Attitude design"],
        description: "Labubu in soda splash mode, soda-themed figure with electronic components and attitude design.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    {
        id: 50,
        name: "Chip Chaos",
        series: "Wacky Mart Series",
        color: "Chip Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Common",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fchip-chaos.jpg?alt=media",
        features: ["Chip-themed", "Electronic components", "PVC/ABS figure", "Attitude design"],
        description: "Labubu in chip chaos mode, chip-themed figure with electronic components and attitude design.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    {
        id: 51,
        name: "Gum Gobble",
        series: "Wacky Mart Series",
        color: "Gum Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Common",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fgum-gobble.jpg?alt=media",
        features: ["Gum-themed", "Electronic components", "PVC/ABS figure", "Attitude design"],
        description: "Labubu in gum gobble mode, gum-themed figure with electronic components and attitude design.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    {
        id: 52,
        name: "Ice Cream Insanity",
        series: "Wacky Mart Series",
        color: "Ice Cream Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Common",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 20, max: 35 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fice-cream-insanity.jpg?alt=media",
        features: ["Ice cream-themed", "Electronic components", "PVC/ABS figure", "Attitude design"],
        description: "Labubu in ice cream insanity mode, ice cream-themed figure with electronic components and attitude design.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.popmart.com/us/collections/labubu"
    },
    {
        id: 53,
        name: "Wacky Cashier (Secret)",
        series: "Wacky Mart Series",
        color: "Cashier Theme",
        size: "5.6-9.5cm / 2.2-3.74 inches",
        rarity: "Ultra Rare",
        releaseDate: "2025-06-13",
        estimatedValue: { min: 100, max: 185 },
        originalPrice: 19.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fwacky-cashier-secret.jpg?alt=media",
        features: ["Secret variant", "1:72 odds", "Cashier design", "Electronic components", "Rare collectible"],
        description: "Rare wacky cashier variant, secret collectible with cashier design and electronic components.",
        dimensions: "5.6-9.5cm / 2.2-3.74 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+wacky+mart+secret"
    },
    // Summer Ride Figure - August 2025 - 1 figure
    {
        id: 54,
        name: "Summer Ride Figure",
        series: "Summer Ride Figure",
        color: "Adventure Theme",
        size: "10cm / 3.94 inches",
        rarity: "Very Rare",
        releaseDate: "2025-08-15",
        estimatedValue: { min: 50, max: 80 },
        originalPrice: 39.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fsummer-ride.jpg?alt=media",
        features: ["Mountain bike", "Adventure theme", "Seasonal release", "Standalone figure", "PVC/ABS"],
        description: "Labubu on mountain bike, seasonal adventure theme; non-blind, standalone hyped release.",
        dimensions: "10cm / 3.94 inches",
        buyLink: "https://www.popmart.com/us/products/3448/labubu-summer-ride-figure"
    },
    // Pin for Love Series - August 2025 - 4 regulars + 1 secret
    {
        id: 55,
        name: "A-Love",
        series: "Pin for Love Series",
        color: "Love Theme",
        size: "10.5cm / 4.13 inches (excluding loop)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fa-love.jpg?alt=media",
        features: ["Letter A theme", "Mini pendant", "Love design", "Smaller scale", "Vinyl plush pendant"],
        description: "Labubu representing love with letter A theme, mini pendant from the hyped recent drop.",
        dimensions: "10.5cm / 4.13 inches (excluding loop)",
        buyLink: "https://www.popmart.com/us/collection/174/pin-for-love"
    },
    {
        id: 56,
        name: "B-Hug",
        series: "Pin for Love Series",
        color: "Hug Theme",
        size: "10.5cm / 4.13 inches (excluding loop)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fb-hug.jpg?alt=media",
        features: ["Letter B theme", "Mini pendant", "Hug design", "Smaller scale", "Vinyl plush pendant"],
        description: "Labubu representing hug with letter B theme, mini pendant from the hyped recent drop.",
        dimensions: "10.5cm / 4.13 inches (excluding loop)",
        buyLink: "https://www.popmart.com/us/collection/174/pin-for-love"
    },
    {
        id: 57,
        name: "C-Kiss",
        series: "Pin for Love Series",
        color: "Kiss Theme",
        size: "10.5cm / 4.13 inches (excluding loop)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fc-kiss.jpg?alt=media",
        features: ["Letter C theme", "Mini pendant", "Kiss design", "Smaller scale", "Vinyl plush pendant"],
        description: "Labubu representing kiss with letter C theme, mini pendant from the hyped recent drop.",
        dimensions: "10.5cm / 4.13 inches (excluding loop)",
        buyLink: "https://www.popmart.com/us/collection/174/pin-for-love"
    },
    {
        id: 58,
        name: "Z-Eternal",
        series: "Pin for Love Series",
        color: "Eternal Theme",
        size: "10.5cm / 4.13 inches (excluding loop)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 15, max: 25 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fz-eternal.jpg?alt=media",
        features: ["Letter Z theme", "Mini pendant", "Eternal design", "Smaller scale", "Vinyl plush pendant"],
        description: "Labubu representing eternal with letter Z theme, mini pendant from the hyped recent drop.",
        dimensions: "10.5cm / 4.13 inches (excluding loop)",
        buyLink: "https://www.popmart.com/us/collection/174/pin-for-love"
    },
    {
        id: 59,
        name: "Love Letter Variant (Secret)",
        series: "Pin for Love Series",
        color: "Love Letter Theme",
        size: "10.5cm / 4.13 inches (excluding loop)",
        rarity: "Ultra Rare",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 80, max: 150 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Flove-letter-secret.jpg?alt=media",
        features: ["Secret variant", "1:72 odds", "Love letter design", "Mini pendant", "Rare collectible"],
        description: "Rare love letter variant, secret collectible mini pendant from the hyped recent drop.",
        dimensions: "10.5cm / 4.13 inches (excluding loop)",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+secret"
    },
    // Mokoko Individual Plush Doll Releases (TBD release dates)
    {
        id: 98,
        name: "Twinkly Fairy Tale",
        series: "Mokoko Individual Plush Dolls",
        color: "Pastel with Sparkle",
        size: "6.69 inches",
        rarity: "Rare",
        releaseDate: "TBD",
        estimatedValue: { min: 100, max: 275 },
        originalPrice: 0.00,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Ftwinkly-fairy-tale.jpg?alt=media",
        features: ["Fairy tale theme", "Vinyl plush pendant", "Sparkling accents"],
        description: "Mokoko in a whimsical fairy tale design, plush pendant with sparkling details.",
        dimensions: "6.69 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=mokoko+twinkly+fairy+tale"
    },
    {
        id: 99,
        name: "Magic the Pumpkin",
        series: "Mokoko Individual Plush Dolls",
        color: "Orange with Green",
        size: "TBD",
        rarity: "Rare",
        releaseDate: "TBD",
        estimatedValue: { min: 80, max: 150 },
        originalPrice: 0.00,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fmagic-the-pumpkin.jpg?alt=media",
        features: ["Pumpkin theme", "Vinyl plush doll", "Magical design"],
        description: "Mokoko with a magical pumpkin theme, plush doll release.",
        dimensions: "TBD",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=mokoko+magic+the+pumpkin"
    },
    {
        id: 100,
        name: "Fall to Spring",
        series: "Mokoko Individual Plush Dolls",
        color: "Pink with Seasonal Tones",
        size: "15.75 inches",
        rarity: "Very Rare",
        releaseDate: "TBD",
        estimatedValue: { min: 200, max: 1700 },
        originalPrice: 0.00,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Ffall-to-spring.jpg?alt=media",
        features: ["Seasonal theme", "Large plush doll", "Pink fur design"],
        description: "Mokoko in a seasonal fall-to-spring transition, large plush doll release.",
        dimensions: "15.75 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=mokoko+fall+to+spring"
    },
    {
        id: 101,
        name: "Close to Sweet",
        series: "Mokoko Individual Plush Dolls",
        color: "Pink with White",
        size: "14.5 inches",
        rarity: "Rare",
        releaseDate: "TBD",
        estimatedValue: { min: 150, max: 300 },
        originalPrice: 0.00,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fclose-to-sweet.jpg?alt=media",
        features: ["Sweet theme", "Vinyl plush doll", "Heart-shaped nose"],
        description: "Mokoko in a sweet-themed design, plush doll with heart-shaped nose.",
        dimensions: "14.5 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=mokoko+close+to+sweet"
    },
    {
        id: 102,
        name: "Blue Diamond",
        series: "Mokoko Individual Plush Dolls",
        color: "Blue with Sparkle",
        size: "6.69 inches",
        rarity: "Rare",
        releaseDate: "TBD",
        estimatedValue: { min: 100, max: 159 },
        originalPrice: 0.00,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fblue-diamond.jpg?alt=media",
        features: ["Diamond theme", "Vinyl plush pendant", "Blue sparkle design"],
        description: "Mokoko with a blue diamond theme, plush pendant release.",
        dimensions: "6.69 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=mokoko+blue+diamond"
    },
    // Zimomo Individual Plush Doll Releases (TBD release dates)
    {
        id: 103,
        name: "I Found You",
        series: "Zimomo Individual Plush Dolls",
        color: "TBD",
        size: "22.8 inches",
        rarity: "Very Rare",
        releaseDate: "TBD",
        estimatedValue: { min: 150, max: 179 },
        originalPrice: 0.00,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fi-found-you.jpg?alt=media",
        features: ["Large plush doll", "Tail design", "Cool leader theme"],
        description: "Zimomo in a 'I Found You' pose, large plush doll with tail.",
        dimensions: "30x25x58cm",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=zimomo+i+found+you"
    },
    {
        id: 104,
        name: "Angel in the Clouds",
        series: "Zimomo Individual Plush Dolls",
        color: "TBD",
        size: "33 inches",
        rarity: "Ultra Rare",
        releaseDate: "TBD",
        estimatedValue: { min: 200, max: 289 },
        originalPrice: 0.00,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fangel-in-the-clouds.jpg?alt=media",
        features: ["Large plush doll", "Angel theme", "Tail design"],
        description: "Zimomo as an angel in the clouds, large plush doll with tail.",
        dimensions: "33x25x58cm",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=zimomo+angel+in+the+clouds"
    },
    // Labubu Pin for Love V4 - August 28, 2025 - 13 regulars + 1 secret per group (A-M and N-Z)
    {
        id: 105,
        name: "A-Love",
        series: "Labubu Pin for Love V4 (A-M)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fa-love-v4.jpg?alt=media",
        features: ["Mini pendant", "Love theme", "A-M group", "Small scale"],
        description: "Labubu A-Love from Pin for Love V4, mini pendant in A-M group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+a-m"
    },
    {
        id: 106,
        name: "B-Hug",
        series: "Labubu Pin for Love V4 (A-M)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fb-hug-v4.jpg?alt=media",
        features: ["Mini pendant", "Hug theme", "A-M group", "Small scale"],
        description: "Labubu B-Hug from Pin for Love V4, mini pendant in A-M group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+a-m"
    },
    {
        id: 107,
        name: "C-Kiss",
        series: "Labubu Pin for Love V4 (A-M)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fc-kiss-v4.jpg?alt=media",
        features: ["Mini pendant", "Kiss theme", "A-M group", "Small scale"],
        description: "Labubu C-Kiss from Pin for Love V4, mini pendant in A-M group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+a-m"
    },
    {
        id: 108,
        name: "D-Heart",
        series: "Labubu Pin for Love V4 (A-M)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fd-heart-v4.jpg?alt=media",
        features: ["Mini pendant", "Heart theme", "A-M group", "Small scale"],
        description: "Labubu D-Heart from Pin for Love V4, mini pendant in A-M group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+a-m"
    },
    {
        id: 109,
        name: "E-Embrace",
        series: "Labubu Pin for Love V4 (A-M)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fe-embrace-v4.jpg?alt=media",
        features: ["Mini pendant", "Embrace theme", "A-M group", "Small scale"],
        description: "Labubu E-Embrace from Pin for Love V4, mini pendant in A-M group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+a-m"
    },
    {
        id: 110,
        name: "F-Forever",
        series: "Labubu Pin for Love V4 (A-M)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Ff-forever-v4.jpg?alt=media",
        features: ["Mini pendant", "Forever theme", "A-M group", "Small scale"],
        description: "Labubu F-Forever from Pin for Love V4, mini pendant in A-M group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+a-m"
    },
    {
        id: 111,
        name: "G-Glory",
        series: "Labubu Pin for Love V4 (A-M)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fg-glory-v4.jpg?alt=media",
        features: ["Mini pendant", "Glory theme", "A-M group", "Small scale"],
        description: "Labubu G-Glory from Pin for Love V4, mini pendant in A-M group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+a-m"
    },
    {
        id: 112,
        name: "H-Harmony",
        series: "Labubu Pin for Love V4 (A-M)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fh-harmony-v4.jpg?alt=media",
        features: ["Mini pendant", "Harmony theme", "A-M group", "Small scale"],
        description: "Labubu H-Harmony from Pin for Love V4, mini pendant in A-M group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+a-m"
    },
    {
        id: 113,
        name: "I-Infinity",
        series: "Labubu Pin for Love V4 (A-M)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fi-infinity-v4.jpg?alt=media",
        features: ["Mini pendant", "Infinity theme", "A-M group", "Small scale"],
        description: "Labubu I-Infinity from Pin for Love V4, mini pendant in A-M group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+a-m"
    },
    {
        id: 114,
        name: "J-Joy",
        series: "Labubu Pin for Love V4 (A-M)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fj-joy-v4.jpg?alt=media",
        features: ["Mini pendant", "Joy theme", "A-M group", "Small scale"],
        description: "Labubu J-Joy from Pin for Love V4, mini pendant in A-M group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+a-m"
    },
    {
        id: 115,
        name: "K-Kindness",
        series: "Labubu Pin for Love V4 (A-M)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fk-kindness-v4.jpg?alt=media",
        features: ["Mini pendant", "Kindness theme", "A-M group", "Small scale"],
        description: "Labubu K-Kindness from Pin for Love V4, mini pendant in A-M group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+a-m"
    },
    {
        id: 116,
        name: "L-Love Eternal",
        series: "Labubu Pin for Love V4 (A-M)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fl-love-eternal-v4.jpg?alt=media",
        features: ["Mini pendant", "Love Eternal theme", "A-M group", "Small scale"],
        description: "Labubu L-Love Eternal from Pin for Love V4, mini pendant in A-M group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+a-m"
    },
    {
        id: 117,
        name: "M-Magic",
        series: "Labubu Pin for Love V4 (A-M)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fm-magic-v4.jpg?alt=media",
        features: ["Mini pendant", "Magic theme", "A-M group", "Small scale"],
        description: "Labubu M-Magic from Pin for Love V4, mini pendant in A-M group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+a-m"
    },
    {
        id: 118,
        name: "A-M Secret Variant",
        series: "Labubu Pin for Love V4 (A-M)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Ultra Rare",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 80, max: 150 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fa-m-secret-v4.jpg?alt=media",
        features: ["Secret variant", "1:72 odds", "A-M group", "Mini pendant", "Rare collectible"],
        description: "Secret variant from Pin for Love V4 A-M group, rare mini pendant.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+a-m+secret"
    },
    {
        id: 119,
        name: "N-Nurture",
        series: "Labubu Pin for Love V4 (N-Z)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fn-nurture-v4.jpg?alt=media",
        features: ["Mini pendant", "Nurture theme", "N-Z group", "Small scale"],
        description: "Labubu N-Nurture from Pin for Love V4, mini pendant in N-Z group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+n-z"
    },
    {
        id: 120,
        name: "O-Optimism",
        series: "Labubu Pin for Love V4 (N-Z)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fo-optimism-v4.jpg?alt=media",
        features: ["Mini pendant", "Optimism theme", "N-Z group", "Small scale"],
        description: "Labubu O-Optimism from Pin for Love V4, mini pendant in N-Z group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+n-z"
    },
    {
        id: 121,
        name: "P-Passion",
        series: "Labubu Pin for Love V4 (N-Z)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fp-passion-v4.jpg?alt=media",
        features: ["Mini pendant", "Passion theme", "N-Z group", "Small scale"],
        description: "Labubu P-Passion from Pin for Love V4, mini pendant in N-Z group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+n-z"
    },
    {
        id: 122,
        name: "Q-Quiet",
        series: "Labubu Pin for Love V4 (N-Z)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fq-quiet-v4.jpg?alt=media",
        features: ["Mini pendant", "Quiet theme", "N-Z group", "Small scale"],
        description: "Labubu Q-Quiet from Pin for Love V4, mini pendant in N-Z group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+n-z"
    },
    {
        id: 123,
        name: "R-Romance",
        series: "Labubu Pin for Love V4 (N-Z)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fr-romance-v4.jpg?alt=media",
        features: ["Mini pendant", "Romance theme", "N-Z group", "Small scale"],
        description: "Labubu R-Romance from Pin for Love V4, mini pendant in N-Z group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+n-z"
    },
    {
        id: 124,
        name: "S-Serenity",
        series: "Labubu Pin for Love V4 (N-Z)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fs-serenity-v4.jpg?alt=media",
        features: ["Mini pendant", "Serenity theme", "N-Z group", "Small scale"],
        description: "Labubu S-Serenity from Pin for Love V4, mini pendant in N-Z group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+n-z"
    },
    {
        id: 125,
        name: "T-Trust",
        series: "Labubu Pin for Love V4 (N-Z)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Ft-trust-v4.jpg?alt=media",
        features: ["Mini pendant", "Trust theme", "N-Z group", "Small scale"],
        description: "Labubu T-Trust from Pin for Love V4, mini pendant in N-Z group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+n-z"
    },
    {
        id: 126,
        name: "U-Unity",
        series: "Labubu Pin for Love V4 (N-Z)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fu-unity-v4.jpg?alt=media",
        features: ["Mini pendant", "Unity theme", "N-Z group", "Small scale"],
        description: "Labubu U-Unity from Pin for Love V4, mini pendant in N-Z group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+n-z"
    },
    {
        id: 127,
        name: "V-Victory",
        series: "Labubu Pin for Love V4 (N-Z)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fv-victory-v4.jpg?alt=media",
        features: ["Mini pendant", "Victory theme", "N-Z group", "Small scale"],
        description: "Labubu V-Victory from Pin for Love V4, mini pendant in N-Z group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+n-z"
    },
    {
        id: 128,
        name: "W-Wonder",
        series: "Labubu Pin for Love V4 (N-Z)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fw-wonder-v4.jpg?alt=media",
        features: ["Mini pendant", "Wonder theme", "N-Z group", "Small scale"],
        description: "Labubu W-Wonder from Pin for Love V4, mini pendant in N-Z group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+n-z"
    },
    {
        id: 129,
        name: "X-Xtra",
        series: "Labubu Pin for Love V4 (N-Z)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fx-xtra-v4.jpg?alt=media",
        features: ["Mini pendant", "Xtra theme", "N-Z group", "Small scale"],
        description: "Labubu X-Xtra from Pin for Love V4, mini pendant in N-Z group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+n-z"
    },
    {
        id: 130,
        name: "Y-Yes",
        series: "Labubu Pin for Love V4 (N-Z)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fy-yes-v4.jpg?alt=media",
        features: ["Mini pendant", "Yes theme", "N-Z group", "Small scale"],
        description: "Labubu Y-Yes from Pin for Love V4, mini pendant in N-Z group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+n-z"
    },
    {
        id: 131,
        name: "Z-Zen",
        series: "Labubu Pin for Love V4 (N-Z)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Common",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 30, max: 39 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fz-zen-v4.jpg?alt=media",
        features: ["Mini pendant", "Zen theme", "N-Z group", "Small scale"],
        description: "Labubu Z-Zen from Pin for Love V4, mini pendant in N-Z group.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+n-z"
    },
    {
        id: 132,
        name: "N-Z Secret Variant",
        series: "Labubu Pin for Love V4 (N-Z)",
        color: "TBD",
        size: "4.1 inches (10.5cm)",
        rarity: "Ultra Rare",
        releaseDate: "2025-08-28",
        estimatedValue: { min: 80, max: 150 },
        originalPrice: 12.99,
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/YOUR_PROJECT_ID.appspot.com/o/labubu-images%2Fn-z-secret-v4.jpg?alt=media",
        features: ["Secret variant", "1:72 odds", "N-Z group", "Mini pendant", "Rare collectible"],
        description: "Secret variant from Pin for Love V4 N-Z group, rare mini pendant.",
        dimensions: "10.5cm / 4.1 inches",
        buyLink: "https://www.ebay.com/sch/i.html?_nkw=labubu+pin+for+love+v4+n-z+secret"
    }
];
