name: iOS Build for TestFlight

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        cd ios
        pod repo update
        pod install --verbose --no-repo-update
        
    - name: Build iOS app
      run: |
        cd ios
        xcodebuild -workspace LabubuUniverse.xcworkspace \
                   -scheme LabubuUniverse \
                   -configuration Release \
                   -destination generic/platform=iOS \
                   -archivePath LabubuUniverse.xcarchive \
                   archive
                   
    - name: Export IPA
      run: |
        cd ios
        xcodebuild -exportArchive \
                   -archivePath LabubuUniverse.xcarchive \
                   -exportPath ./build \
                   -exportOptionsPlist ExportOptions.plist
                   
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: LabubuUniverse-iOS
        path: ios/build/*.ipa
